[package]
name = "lade-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs-next = "2.0.0"
indicatif = "0.17.11"
reqwest = { version = "0.12.12", features = ["blocking"] }
zip = "2.2.2"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"