name: Release Build on macOS

on:
  workflow_dispatch: # 手動トリガー
  # 定期実行
  schedule:
    # 毎週金曜日午後3時(UTC)
    - cron: "0 16 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Build
      run: |
        cd lade-installer
        cargo build --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: installer-weekly-macos-build
        path: lade-installer/target/release/lade-installer
