name: Release Build on Linux

on:
  workflow_dispatch: # 手動トリガー
  # 定期実行
  schedule:
    # 毎週金曜日午後3時(UTC)
    - cron: "0 15 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Build
      run: |
        cd lade-installer
        cargo build --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: installer-weekly-linux-build
        path: lade-installer/target/release/lade-installer
