name: Release Build on Windows

on:
  workflow_dispatch: # 手動トリガー
  # 定期実行
  schedule:
    # 毎週金曜日午後3時(UTC)
    - cron: "0 17 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: |
        cd lade-installer
        cargo build --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lade-weekly-windows-build
        path: installer\target\release\installer.exe
